[package]
name = "uvr-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
openvino = ["uvr-core/openvino"]

[[bin]]
name = "uvr"
path = "src/main.rs"

[dependencies]
uvr-core = { workspace = true, features = ["audio-io", "burn-cpu"] }
anyhow = "1.0"
ctrlc = "=3.5.0"

[lints]
workspace = true
