[package]
name = "uvr-gui"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
custom-protocol = ["tauri/custom-protocol"]
openvino = ["uvr-core/openvino"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "=2.7.2"
serde = { version = "1", features = ["derive"] }
uvr-core = { workspace = true, features = ["burn-cpu", "audio-io", "model-download"] }

[dev-dependencies]
serde_json = "1.0.151"

[lints]
workspace = true
